# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Roger Chi-Jen Lo
description:      
Roger Chi-Jen Lo (羅啟仁) is a MS student in the Department of Communication Engineering in National Taiwan University; he received his BS degree from the Department of Electrical Engineering, National Taiwan University. He is recently under the mentorship of Prof. Tsung-Nan Lin. For any other details, just survey this website, or feel free to contact him via email: <a href="intelisef47@gmail.com" target="_blank">intelisef47@gmail.com</a>. Have a nice day!
url:              http://RogerLo47.github.io
baseurl:          /

author:
  name:           'Lo Chi-Jen'
  url:            https://www.facebook.com/roger.lo.47.81

paginate:         5
