# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Roger Chi-Jen Lo
description:      'NTUEE / NTU GICE'
url:              http://RogerLo47.github.io
baseurl:          /

author:
name:             'Lo Chi-Jen'
url:              https://www.facebook.com/roger.lo.47.81

paginate:         5
