# Dependencies
markdown:         redcarpet
redcarpet:        
extensions:       ["tables", "autolink", "strikethrough", 
"space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter:      pygments

# Permalinks
permalink:        none

# Setup
title:            Roger Chi-Jen Lo
description:      NTUEE / NTU GICE
avatar:           "/img/profile.jpg"
url:              "https://RogerLo47.github.io"
baseurl:          "/"

include:          ['_posts']

author:           Roger Lo
name:             Lo Chi-Jen
url:              https://www.facebook.com/roger.lo.47.81
email:            intelisef47@gmail.com

paginate:         5
